### ISSUE TITLE
typed-wire vs. protobuf?

### ISSUE THREAD

**Issue by tiziano88** [typed-wire/typed-wire#4]
Hi, thanks for creating this project! I understand perfectly its motivation and I also share similar thoughts  and ideas about this issue; in fact, I have recently started approaching the same problem but from a slightly different angle, namely aiming at providing a [protobuf](https://developers.google.com/protocol-buffers/) generator for Elm, in order to make it easy to integrate an Elm front-end with a generic back-end that also uses protobuf JSON serialization for its API (and I'm in the process of building a sample full-stack app using a Go back-end to demonstrate this). You can see the current progress here: https://github.com/tiziano88/elm-protobuf . I'm just curious whether protobuf is something you have heard about / considered before starting this project?

**Comment by tiziano88** [comment]
Also, https://capnproto.org/language.html is yet another possible alternative that I did not initially consider, which is actually probably even more suitable than protobuf... Maybe I should actually switch to that for my project? :smile:

**Comment by agrafix** [comment]
See https://www.reddit.com/r/haskell/comments/468fvj/typedwire_language_independent_typesafe/d03szzp :-)
